### PR TITLE
Feature/suit 13272 design an api

### PR DESCRIPTION
**Pull request by AntonSBilan**
SUIT-13272 - Design an API for the translation module

### CODE REVIEW

**Comment by givehug** [comment]
@AntonSBilan You could also  add test definition files with type for TestLines, LineResults and package API itself.

**Comment by AntonSBilan** [comment]
@givehug I thought we will add them to the project during implementation maybe to some d.ts file, or do you want it to be in readme file?

**Comment by givehug** [comment]
> @givehug I thought we will add them to the project during implementation maybe to some d.ts file, or do you want it to be in readme file?

I meant d.ts. We can add during implementation, no problem.

**Comment by AntonSBilan** [comment]
> > @givehug I thought we will add them to the project during implementation maybe to some d.ts file, or do you want it to be in readme file?
> 
> I meant d.ts. We can add during implementation, no problem.

maybe during implementation is better as probably we will want to reuse it for fe project, maybe it make sense extract it to separate project with type definitions so translation module and fe will reference same types

**Pull request closed without merging**
